/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package mil.yaye.yours.control.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.MappingDispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 03-26-2009
 * 
 * XDoclet definition:
 * @struts.action input="/viewcomment.do" parameter="viewcomment" validate="true"
 */
public class OthersAction extends MappingDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method viewcomment
	 * 查看用户对商品的评论
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward viewcomment(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return null;
	}
}