/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package mil.yaye.yours.control.action;

import java.util.Enumeration;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.MappingDispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 12-04-2008
 * 
 * XDoclet definition:
 * @struts.action parameter="mehod"
 */
public class PreprocessAction extends MappingDispatchAction {
	
	private Logger logger = Logger.getLogger(PreprocessAction.class.getName());
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward registToken(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(request.getSession(false) == null){
			logger.info("在还没有saveToken前还没有开启会话session.......");
		}
		saveToken(request);
		if(request.getSession(false) != null){
			logger.info("此时session已不为null了........");
		}
		Enumeration attrs = request.getSession(false).getAttributeNames();
		while(attrs.hasMoreElements()){
			Object attr = attrs.nextElement();
			logger.info("Token令牌为:" + request.getSession(false).getAttribute((String)attr));
		}
		return new ActionForward("/regist.do");
	}
}