/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package mil.yaye.yours.engine.control.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.MappingDispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 01-26-2009
 * 
 * XDoclet definition:
 * @struts.action parameter="method"
 */
public class GuideAction extends MappingDispatchAction {
	/*
	 * Generated Methods
	 * 我这样写的目的是既让服务器端的任务计划能请求调用,也能让客户端请求调用
	 */

	public ActionForward categoryGuide(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String category = request.getParameter("category");
		
//		List<?> list = service.search***();
//		request.setAttribute("", list);
		ActionForward forward = new ActionForward(category+".jsp");
		return forward;
	}
	public ActionForward categoryBrandsGuide(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String category = request.getParameter("category");
		String brand = request.getParameter("brand");
		
//		List<?> list = service.search***();
//		request.setAttribute("", list);
		ActionForward forward = new ActionForward();
		return null;
	}
	public ActionForward brandsGuide(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String brand = request.getParameter("brand");
		
		ActionForward forward = new ActionForward(); 
		return null;
	}
}