/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package mil.yaye.yours.engine.control.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import mil.yaye.yours.engine.service.EngineService;
import mil.yaye.yours.factory.BeanFactory;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
//import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.MappingDispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 02-24-2009
 * 
 * XDoclet definition:
 * @struts.action path="/manualEngineControlCenter" name="manualEngineControlCenterForm" input="/manualEngineControlCenter.jsp" parameter="method" scope="request" validate="true"
 */
public class ManualEngineControlCenterAction extends MappingDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
//		DynaActionForm manualEngineControlCenterForm = (DynaActionForm) form;
		BeanFactory beanFactory = BeanFactory.getInstance(null);
		String id = "EngineServiceImpl";
		EngineService service = (EngineService) beanFactory.getBean(id);
		//手动调用引擎service
		service.manual(getServlet().getServletContext());
		
		return null;
	}
}