/*function writeheader(){
	document.getElementById('header').innerHTML=
	"<div id='preface_wrapper'>"
		+"<div id='preface_left'>"
			+"<img src='images/logo.jpg' alt='红玫瑰商城' width='210' height='97' />"
		+"</div>"
		+"<div id='preface_right'>"
			+"<div id='right_up'>"
				+"<div id='three'>"
					+"<dl>"
						+"<dd class='thre'><a href='#'>购物车</a></dd>"
						+"<dd class='thre'><a href='#'>我的账户</a></dd>"
						+"<dd class='thre'><a href='#'>帮助</a></dd>"
					+"</dl>"
				+"</div>"
				+"<div id='logon'>"
					+"<a href='javascript:login();'>${UserInfoDTO.getUsername()}</a>|<a href='#'>安全退出</a>"
				+"</div>"
			+"</div>"
			+"<div style='clear:both'></div>"
			+"<div class='nav' id='navigator'>"
				+"<div class='nav-right'></div>"
				+"<div class='nav-left'></div>"
				+"<div class='nav-bg'>"
					+"<ul>"
						+"<li class='current'><a href='http://localhost:8077/Yaye/index.html'><span>Home</span></a></li>"
						+"<li><a href='#'><span>女性内衣</span></a></li>"
						+"<li><a href='#'><span>服饰</span></a></li>"
						+"<li><a href='#'><span>化妆品</span></a></li>"
						+"<li><a href='#'><span>数码</span></a></li>"
						+"<li><a href='#'><span>鲜花</span></a></li>"
						+"<li><a href='#'><span>时尚杂志</span></a></li>"
					+"</ul>"
				+"</div>"
			+"</div>"
		+"</div>"
	+"</div>"
	+"<div style='clear:both;'></div>"
	+"<div id='searchbar'>"
		+"<div id='searchbar_wrapper'>"
			+"<div class='magnifier'>"
				+"<img src='images/seach_1.gif' width='24' height='31' alt=''/></div>"
			+"<div class='searchform'>"
				+"<select id='classification' name='type'>"
				  +"<script type='text/javascript'>"
				  	+"FillSearchwords();"
				  +"</script>"
				+"</select>"
				+"<input type='text' id='txtSearchWord' class='' />"
				+"<input id='searchbutton' type='button' value='搜索' onClick='doSearch('http://mall.sina.com.cn/srh');'/>"
			+"</div>"
			+"<div class='searchkeywords'>"
				+"<img src='images/keywords.gif' width='67' height='13'/>"
				+"<span class='' id='keywords'>"
					+"<script type='text/javascript'>FillKeywords();</script>"
				+"</span>"
			+"</div>"
		+"</div>"
	+"</div>";
}*/
function _writeheader(){
	document.getElementById('header').innerHTML=
	"<div id='preface_wrapper'>"
		+"<div id='preface_left'>"
			+"<img src='http://localhost:8077/Yaye/images/logo.jpg' alt='红玫瑰商城' width='210' height='97' />"
		+"</div>"
		+"<div id='preface_right'>"
			+"<div id='right_up'>"
				+"<div id='three'>"
					+"<dl>"
						+"<dd class='thre'><a href='#'>购物车</a></dd>"
						+"<dd class='thre'><a href='#'>我的账户</a></dd>"
						+"<dd class='thre'><a href='#'>帮助</a></dd>"
					+"</dl>"
				+"</div>"
				+"<div id='logon'>"
					+"<a href='javascript:login();'><%=userInfoDTO.getUsername()%></a>&nbsp;|&nbsp;<a href='#'>安全退出</a>"
				+"</div>"
			+"</div>"
			+"<div style='clear:both'></div>"
			+"<div class='nav' id='navigator'>"
				+"<div class='nav-right'></div>"
				+"<div class='nav-left'></div>"
				+"<div class='nav-bg'>"
					+"<ul>"
						+"<li class='current'><a href='http://localhost:8077/Yaye/index.html'><span>Home</span></a></li>"
						+"<li><a href='#'><span>女性内衣</span></a></li>"
						+"<li><a href='#'><span>服饰</span></a></li>"
						+"<li><a href='#'><span>化妆品</span></a></li>"
						+"<li><a href='#'><span>数码</span></a></li>"
						+"<li><a href='#'><span>鲜花</span></a></li>"
						+"<li><a href='#'><span>时尚杂志</span></a></li>"
					+"</ul>"
				+"</div>"
			+"</div>"
		+"</div>"
	+"</div>"
	+"<div style='clear:both;'></div>"
	+"<div id='searchbar'>"
		+"<div id='searchbar_wrapper'>"
			+"<div class='magnifier'>"
				+"<img src='http://localhost:8077/Yaye/images/seach_1.gif' width='24' height='31' alt=''/></div>"
			+"<div class='searchform'>"
				+"<select id='classification' name='type'>"
				  +"<option value='0'>所有商品</option>"
				  +"<option value='1'>电脑/网络/办公/耗材</option>"
				  +"<option value='2'>数码视听/相机/摄影摄像</option>"
				  +"<option value='3'>随身视听/家电</option>"
				  +"<option value='4'>手机/通讯设备/数字卡</option>"
				  +"<option value='5'>服装鞋帽/箱包/服饰配件</option>"
				  +"<option value='6'>珠宝/眼镜/手表</option>"
				  +"<option value='7'>健康美容</option>"
				  +"<option value='8'>家居日用/装饰/宠物</option>"
				  +"<option value='9'>礼品/鲜花</option>"
				  +"<option value='10'>文具/玩具/卡通/模型/游戏</option>"
				  +"<option value='11'>运动/户外/军品</option>"
				  +"<option value='13'>图书/报刊/杂志</option>"
				  +"<option value='17'>电影/电视/音乐/曲艺</option>"
				  +"<option value='5455'>教育/票务/生活服务</option>"
				  +"<option value='8924'>网游/彩票/通讯/邮箱/教育</option>"
				+"</select>"
				+"<input type='text' id='txtSearchWord' class='' />"
				+"<input id='searchbutton' type='button' value='搜索' onClick='doSearch('http://mall.sina.com.cn/srh');'/>"
			+"</div>"
			+"<div class='searchkeywords'>"
				+"<img src='http://localhost:8077/Yaye/images/keywords.gif' width='67' height='13'/>"
				+"<span class='' id='keywords'>&nbsp;"
					+"<a href='' target=_blank class='ti'>激情系列</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>MP4</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>睡衣</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>靴子</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>铂金</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>吊坠</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>保湿</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>诺基亚</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>秀发飘飞</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>美白</a>&nbsp;"
					+"<a href='' target=_blank class='ti'>丝芙兰</a>&nbsp;"
				+"</span>"
			+"</div>"
		+"</div>"
	+"</div>";
}
/*"<script type='text/javascript' src='js/KeywordsValue.js'></script>"
+"<script type='text/javascript' src='js/SearchwordsValue.js'></script>"
+"<script type='text/javascript' src='js/NavwordsValue.js'></script>"
+"<script type='text/javascript' src='js/header.js'></script>"
+"<script type='text/javascript' src='js/Header_helper.js'></script>"*/
