function writeheader(){
	document.getElementById('header').innerHTML=
	"<div id='preface_wrapper'>"
		+"<div id='preface_left'>"
			+"<img src='http://localhost:8077/Yaye/images/logo.jpg' alt='红玫瑰商城' width='210' height='97' />"
		+"</div>"
		+"<div id='preface_right'>"
			+"<div id='right_up'>"
				+"<div id='three'>"
					+"<span id='thre1' class='thre'><a href='http://localhost:8077/Yaye/buy/myshopcart.do'>购物车</a></span>"
					+"<span id='thre2' class='thre'><a href='#'>我的账户</a></span>"
					+"<span id='thre2' class='thre'><a href='#'>帮助</a></span>"
				+"</div>"
				+"<div id='logon'>"
					+"<a href='http://localhost:8077/Yaye/logon.html'>登陆</a>|<a href='http://localhost:8077/Yaye/regist.html'>注册</a>"
				+"</div>"
			+"</div>"
			+"<div style='clear:both'></div>"
			+"<div class='nav' id='navigator'>"
				+"<div class='nav-right'></div>"
				+"<div class='nav-left'></div>"
				+"<div class='nav-bg'>"
					+"<ul id='nav_listxxx'>"
					+"</ul>"
				+"</div>"
			+"</div>"
		+"</div>"
	+"</div>"
	+"<div style='clear:both;'></div>"
	+"<div id='searchbar'>"
		+"<div id='searchbar_wrapper'>"
			+"<div class='magnifier'>"
				+"<img src='http://localhost:8077/Yaye/images/seach_1.gif' width='24' height='31' alt=''/></div>"
			+"<div class='searchform'>"
				+"<select id='classification' name='type'>"
				+"</select>"
				+"<input type='text' id='txtSearchWord' class='' />"
				+"<input id='searchbutton' type='button' value='搜索' onClick='doSearch('http://mall.sina.com.cn/srh');'/>"
			+"</div>"
			+"<div class='searchkeywords'>"
				+"<img src='http://localhost:8077/Yaye/images/keywords.gif' width='67' height='13'/>"
				+"<span class='' id='keywords'>&nbsp;"
				+"</span>"
			+"</div>"
		+"</div>"
	+"</div>";
}
